name = "golf-stats"
pages_build_output_dir = "public"
compatibility_date = "2026-10-01"

[[d1_databases]]
binding = "DB"
database_name = "golf-stats"
database_id = "8b960c74-31d3-401a-8b4b-0cfb94a2dfa2"
migrations_dir = "migrations"
